import { Op } from 'sequelize';
import Campaign from '../models/Campaign';
import DeliveryAddress from '../models/DeliveryAddress';
import Product from '../models/Product';
import Store from '../models/Store';
import env from '../config/env';
import logger from '../utils/logger';
import { BadRequestError, NotFoundError } from '../utils/errors';

interface QuoteItemInput {
  product_id: number;
  quantity: number;
}

interface QuoteInput {
  userId: number;
  items: QuoteItemInput[];
  deliveryAddressId?: number;
  shippingAddress?: Record<string, any>;
  delivery_mode?: 'normal' | 'instant'; // Defaults to 'normal' if not specified
}

interface NormalizedLocation {
  latitude?: number;
  longitude?: number;
  place_id?: string;
  formatted_address?: string;
  country?: string;
  city?: string;
  street?: string;
  address_description?: string;
  vicinity?: string;
  source?: 'manual' | 'autocomplete' | 'current_location';
}

interface FeeQuoteResult {
  shipping_fee: number;
  distance_km: number | null;
  used_cache: boolean;
  free_delivery: boolean;
  free_delivery_reason?: string;
  delivery_mode: 'normal' | 'instant';
  store: {
    id: number;
    name: string;
    normal_per_km_fee: number;
    normal_base_fee: number;
    instant_per_km_fee: number;
    instant_base_fee: number;
    instant_delivery_enabled: boolean;
  };
}

const DEFAULT_DELIVERY_FEE_UGX = 3500;

export class DeliveryPricingService {
  private static get mapsKey(): string {
    return env.GOOGLE_MAPS_API_KEY || '';
  }

  private static get countryCode(): string {
    return env.GOOGLE_MAPS_COUNTRY_CODE || 'ug';
  }

  private static toNumber(value: any): number | undefined {
    if (value === null || value === undefined || value === '') return undefined;
    const parsed = Number(value);
    return Number.isFinite(parsed) ? parsed : undefined;
  }

  private static toRadians(deg: number): number {
    return (deg * Math.PI) / 180;
  }

  static haversineKm(lat1: number, lon1: number, lat2: number, lon2: number): number {
    const r = 6371;
    const dLat = this.toRadians(lat2 - lat1);
    const dLon = this.toRadians(lon2 - lon1);
    const a =
      Math.sin(dLat / 2) ** 2 +
      Math.cos(this.toRadians(lat1)) * Math.cos(this.toRadians(lat2)) * Math.sin(dLon / 2) ** 2;
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
    return r * c;
  }

  static async getOfficialStore(): Promise<Store> {
    const store = await Store.findOne({
      where: { is_active: true },
      order: [
        ['is_official', 'DESC'],
        ['id', 'ASC'],
      ],
    });

    if (store) return store;

    const fallback = await Store.create({
      name: env.STORE_NAME || 'Nalmart Official Store',
      country: 'Uganda',
      is_active: true,
      is_official: true,
      per_km_delivery_fees: 700,
      base_delivery_fee: DEFAULT_DELIVERY_FEE_UGX,
      metadata: { autogenerated: true },
    });

    return fallback;
  }

  static async searchAddressSuggestions(input: string, sessionToken?: string): Promise<any[]> {
    const q = String(input || '').trim();
    if (!q || q.length < 3) return [];

    if (!this.mapsKey) {
      logger.warn('[DeliveryPricing] GOOGLE_MAPS_API_KEY missing: autocomplete disabled');
      return [];
    }

    const params = new URLSearchParams({
      input: q,
      key: this.mapsKey,
      components: `country:${this.countryCode}`,
    });

    if (sessionToken) params.set('sessiontoken', sessionToken);

    const url = `https://maps.googleapis.com/maps/api/place/autocomplete/json?${params.toString()}`;
    const response = await fetch(url);
    if (!response.ok) return [];

    const payload: any = await response.json();
    if (payload.status !== 'OK' && payload.status !== 'ZERO_RESULTS') {
      logger.warn(`[DeliveryPricing] Autocomplete status: ${payload.status}`);
      return [];
    }

    return (payload.predictions || []).map((p: any) => ({
      place_id: p.place_id,
      description: p.description,
      main_text: p.structured_formatting?.main_text,
      secondary_text: p.structured_formatting?.secondary_text,
    }));
  }

  static async resolveAddressLocation(input: {
    place_id?: string;
    latitude?: number;
    longitude?: number;
    address?: string;
    sessionToken?: string;
    source?: 'manual' | 'autocomplete' | 'current_location';
  }): Promise<NormalizedLocation> {
    const source = input.source || 'manual';

    if (!this.mapsKey) {
      return {
        latitude: input.latitude,
        longitude: input.longitude,
        formatted_address: input.address,
        source,
      };
    }

    if (input.place_id) {
      const params = new URLSearchParams({
        place_id: input.place_id,
        key: this.mapsKey,
        fields: 'place_id,formatted_address,geometry,address_component,name',
      });
      if (input.sessionToken) params.set('sessiontoken', input.sessionToken);

      const url = `https://maps.googleapis.com/maps/api/place/details/json?${params.toString()}`;
      const response = await fetch(url);
      if (!response.ok) throw new BadRequestError('Failed to resolve selected address');
      const payload: any = await response.json();
      if (payload.status !== 'OK' || !payload.result) {
        throw new BadRequestError('Could not resolve selected address details');
      }

      return this.fromGoogleAddressComponents(
        payload.result.address_components || [],
        payload.result.formatted_address,
        payload.result.place_id,
        payload.result.geometry?.location?.lat,
        payload.result.geometry?.location?.lng,
        source,
      );
    }

    if (input.latitude !== undefined && input.longitude !== undefined) {
      const params = new URLSearchParams({
        latlng: `${input.latitude},${input.longitude}`,
        key: this.mapsKey,
      });
      const url = `https://maps.googleapis.com/maps/api/geocode/json?${params.toString()}`;
      const response = await fetch(url);
      if (!response.ok) throw new BadRequestError('Failed to resolve current location');

      const payload: any = await response.json();
      const first = payload.results?.[0];
      if (!first) {
        return {
          latitude: input.latitude,
          longitude: input.longitude,
          formatted_address: undefined,
          source,
        };
      }

      return this.fromGoogleAddressComponents(
        first.address_components || [],
        first.formatted_address,
        first.place_id,
        input.latitude,
        input.longitude,
        source,
      );
    }

    const rawAddress = String(input.address || '').trim();
    if (rawAddress) {
      const params = new URLSearchParams({
        address: rawAddress,
        key: this.mapsKey,
        components: `country:${this.countryCode}`,
      });
      const url = `https://maps.googleapis.com/maps/api/geocode/json?${params.toString()}`;
      const response = await fetch(url);
      if (response.ok) {
        const payload: any = await response.json();
        const first = payload.results?.[0];
        if (first) {
          return this.fromGoogleAddressComponents(
            first.address_components || [],
            first.formatted_address,
            first.place_id,
            first.geometry?.location?.lat,
            first.geometry?.location?.lng,
            source,
          );
        }
      }
    }

    return { formatted_address: rawAddress || undefined, source };
  }

  private static fromGoogleAddressComponents(
    components: any[],
    formattedAddress?: string,
    placeId?: string,
    lat?: number,
    lng?: number,
    source: 'manual' | 'autocomplete' | 'current_location' = 'manual',
  ): NormalizedLocation {
    const get = (types: string[]): string | undefined => {
      const found = components.find((c: any) => types.some((t) => c.types?.includes(t)));
      return found?.long_name;
    };

    const streetNumber = get(['street_number']);
    const route = get(['route']);
    const neighborhood = get(['neighborhood', 'sublocality', 'sublocality_level_1']);
    const city = get(['locality', 'administrative_area_level_2']) || get(['administrative_area_level_1']);
    const country = get(['country']);

    return {
      latitude: this.toNumber(lat),
      longitude: this.toNumber(lng),
      place_id: placeId,
      formatted_address: formattedAddress,
      country,
      city,
      street: [streetNumber, route].filter(Boolean).join(' ').trim() || route,
      address_description: neighborhood,
      vicinity: neighborhood || city,
      source,
    };
  }

  private static async allItemsHaveFreeDeliveryCampaign(products: Product[]): Promise<boolean> {
    if (products.length === 0) return false;

    const now = new Date();
    const campaigns = await Campaign.findAll({
      where: {
        is_active: true,
        discount_type: 'free_shipping',
        start_date: { [Op.lte]: now },
        end_date: { [Op.gte]: now },
      },
    });

    if (campaigns.length === 0) return false;

    const productIds = new Set(products.map((p) => Number(p.id)));

    const isCovered = (campaign: Campaign, product: Product): boolean => {
      const applicability = String((campaign as any).applicability || 'all_products');
      const applicableItems = ((campaign as any).applicable_items || []) as number[];

      if (applicability === 'all_products') return true;
      if (applicability === 'specific_products') {
        return applicableItems.map(Number).includes(Number(product.id));
      }
      if (applicability === 'specific_categories') {
        return applicableItems.map(Number).includes(Number(product.category_id));
      }
      return false;
    };

    for (const product of products) {
      let covered = false;
      for (const campaign of campaigns) {
        if (isCovered(campaign, product)) {
          covered = true;
          break;
        }
      }
      if (!covered) return false;
    }

    for (const id of productIds) {
      if (!Number.isFinite(id)) return false;
    }

    return true;
  }

  private static async findNearbyCachedAddressDistance(
    storeId: number,
    latitude: number,
    longitude: number,
  ): Promise<number | null> {
    const delta = 0.004; // ~440m

    const nearby = await DeliveryAddress.findAll({
      where: {
        latitude: { [Op.between]: [latitude - delta, latitude + delta] },
        longitude: { [Op.between]: [longitude - delta, longitude + delta] },
        distance_km_from_store: { [Op.not]: null },
      },
      order: [['updated_at', 'DESC']],
      limit: 80,
    });

    let best: { distToTarget: number; cachedDistance: number } | null = null;
    for (const addr of nearby) {
      const lat = this.toNumber((addr as any).latitude);
      const lng = this.toNumber((addr as any).longitude);
      const cachedDistance = this.toNumber((addr as any).distance_km_from_store);
      if (lat === undefined || lng === undefined || cachedDistance === undefined) continue;

      const distToTarget = this.haversineKm(latitude, longitude, lat, lng);
      if (distToTarget <= 0.35 && (!best || distToTarget < best.distToTarget)) {
        best = { distToTarget, cachedDistance };
      }
    }

    return best?.cachedDistance ?? null;
  }

  private static async googleDistanceKm(
    originLat: number,
    originLng: number,
    destinationLat: number,
    destinationLng: number,
  ): Promise<number | null> {
    if (!this.mapsKey) return null;

    const params = new URLSearchParams({
      origins: `${originLat},${originLng}`,
      destinations: `${destinationLat},${destinationLng}`,
      key: this.mapsKey,
      mode: 'driving',
      units: 'metric',
    });

    const url = `https://maps.googleapis.com/maps/api/distancematrix/json?${params.toString()}`;
    const response = await fetch(url);
    if (!response.ok) return null;

    const payload: any = await response.json();
    if (payload.status !== 'OK') {
      logger.warn(`[DeliveryPricing] DistanceMatrix status: ${payload.status}`);
      return null;
    }

    const element = payload.rows?.[0]?.elements?.[0];
    if (!element || element.status !== 'OK') return null;

    const meters = Number(element.distance?.value || 0);
    if (!Number.isFinite(meters) || meters <= 0) return null;
    return meters / 1000;
  }

  private static async computeDistanceFromStore(
    store: Store,
    latitude: number,
    longitude: number,
  ): Promise<{ distanceKm: number | null; usedCache: boolean }> {
    const storeLat = this.toNumber((store as any).latitude);
    const storeLng = this.toNumber((store as any).longitude);

    if (storeLat === undefined || storeLng === undefined) {
      return { distanceKm: null, usedCache: false };
    }

    const cached = await this.findNearbyCachedAddressDistance(store.id, latitude, longitude);
    if (cached !== null) {
      return { distanceKm: cached, usedCache: true };
    }

    const distanceKm = await this.googleDistanceKm(storeLat, storeLng, latitude, longitude);
    return { distanceKm, usedCache: false };
  }

  static async estimateDistanceFromOfficialStore(
    latitude: number,
    longitude: number,
  ): Promise<{ distance_km: number | null; used_cache: boolean }> {
    const store = await this.getOfficialStore();
    const { distanceKm, usedCache } = await this.computeDistanceFromStore(store, latitude, longitude);
    return {
      distance_km: distanceKm === null ? null : Number(distanceKm.toFixed(3)),
      used_cache: usedCache,
    };
  }

  static async quoteDeliveryFee(input: QuoteInput): Promise<FeeQuoteResult> {
    if (!Array.isArray(input.items) || input.items.length === 0) {
      throw new BadRequestError('At least one order item is required to quote delivery');
    }

    const uniqueProductIds = Array.from(new Set(input.items.map((item) => Number(item.product_id))));

    const products = await Product.findAll({
      where: { id: uniqueProductIds },
      attributes: ['id', 'category_id', 'free_delivery'],
    });

    if (products.length !== uniqueProductIds.length) {
      throw new NotFoundError('One or more products not found while quoting delivery');
    }

    // Free delivery if every item in the basket has the free_delivery flag set
    const freeByProductFlag = products.every((p) => Boolean((p as any).free_delivery));

    const freeByCampaign = !freeByProductFlag && await this.allItemsHaveFreeDeliveryCampaign(products);

    const store = await this.getOfficialStore();
    
    // Determine delivery mode (default to 'normal' if not specified)
    const deliveryMode = input.delivery_mode || 'normal';
    
    // Get fees based on selected delivery mode
    const perKmFee = deliveryMode === 'instant' 
      ? Number((store as any).instant_per_km_fee || 3000)
      : Number((store as any).normal_per_km_fee || 1500);
    
    const baseFee = deliveryMode === 'instant'
      ? Number((store as any).instant_base_fee || 0)
      : Number((store as any).normal_base_fee || 0);

    if (freeByProductFlag || freeByCampaign) {
      return {
        shipping_fee: 0,
        distance_km: null,
        used_cache: false,
        free_delivery: true,
        free_delivery_reason: freeByProductFlag
          ? 'All basket items include free delivery'
          : 'All basket items are covered by active free-delivery campaigns',
        delivery_mode: deliveryMode,
        store: {
          id: store.id,
          name: store.name,
          normal_per_km_fee: Number((store as any).normal_per_km_fee || 1500),
          normal_base_fee: Number((store as any).normal_base_fee || 0),
          instant_per_km_fee: Number((store as any).instant_per_km_fee || 3000),
          instant_base_fee: Number((store as any).instant_base_fee || 0),
          instant_delivery_enabled: Boolean((store as any).instant_delivery_enabled ?? true),
        },
      };
    }

    let destinationLat: number | undefined;
    let destinationLng: number | undefined;
    let targetAddress: DeliveryAddress | null = null;

    if (input.deliveryAddressId) {
      targetAddress = await DeliveryAddress.findOne({
        where: { id: input.deliveryAddressId, user_id: input.userId },
      });
      if (!targetAddress) throw new NotFoundError('Delivery address not found');

      destinationLat = this.toNumber((targetAddress as any).latitude);
      destinationLng = this.toNumber((targetAddress as any).longitude);
    } else {
      destinationLat = this.toNumber(input.shippingAddress?.latitude);
      destinationLng = this.toNumber(input.shippingAddress?.longitude);
    }

    if (destinationLat === undefined || destinationLng === undefined) {
      return {
        shipping_fee: DEFAULT_DELIVERY_FEE_UGX,
        distance_km: null,
        used_cache: false,
        free_delivery: false,
        free_delivery_reason: 'Distance unavailable; default delivery fee applied',
        delivery_mode: deliveryMode,
        store: {
          id: store.id,
          name: store.name,
          normal_per_km_fee: Number((store as any).normal_per_km_fee || 1500),
          normal_base_fee: Number((store as any).normal_base_fee || 0),
          instant_per_km_fee: Number((store as any).instant_per_km_fee || 3000),
          instant_base_fee: Number((store as any).instant_base_fee || 0),
          instant_delivery_enabled: Boolean((store as any).instant_delivery_enabled ?? true),
        },
      };
    }

    const { distanceKm, usedCache } = await this.computeDistanceFromStore(
      store,
      destinationLat,
      destinationLng,
    );

    if (!distanceKm || !Number.isFinite(distanceKm)) {
      return {
        shipping_fee: DEFAULT_DELIVERY_FEE_UGX,
        distance_km: null,
        used_cache: false,
        free_delivery: false,
        free_delivery_reason: 'Distance API unavailable; default delivery fee applied',
        delivery_mode: deliveryMode,
        store: {
          id: store.id,
          name: store.name,
          normal_per_km_fee: Number((store as any).normal_per_km_fee || 1500),
          normal_base_fee: Number((store as any).normal_base_fee || 0),
          instant_per_km_fee: Number((store as any).instant_per_km_fee || 3000),
          instant_base_fee: Number((store as any).instant_base_fee || 0),
          instant_delivery_enabled: Boolean((store as any).instant_delivery_enabled ?? true),
        },
      };
    }

    const computedFee = Math.max(0, Math.round(baseFee + distanceKm * perKmFee));

    if (targetAddress) {
      await targetAddress.update({
        distance_km_from_store: Number(distanceKm.toFixed(3)),
        distance_calculated_at: new Date(),
      });
    }

    return {
      shipping_fee: computedFee,
      distance_km: Number(distanceKm.toFixed(3)),
      used_cache: usedCache,
      free_delivery: false,
      delivery_mode: deliveryMode,
      store: {
        id: store.id,
        name: store.name,
        normal_per_km_fee: Number((store as any).normal_per_km_fee || 1500),
        normal_base_fee: Number((store as any).normal_base_fee || 0),
        instant_per_km_fee: Number((store as any).instant_per_km_fee || 3000),
        instant_base_fee: Number((store as any).instant_base_fee || 0),
        instant_delivery_enabled: Boolean((store as any).instant_delivery_enabled ?? true),
      },
    };
  }
}

export default DeliveryPricingService;
